### ISSUE TITLE
Gemeentes: nog geen processen-verbaal gepubliceerd (of niet gevonden)

### ISSUE THREAD

**Issue by Sjors** [Sjors/verkiezingen-processen-verbaal#51]
Op het moment dat ik ze probeerde in te voeren, ontbraken de uitslagen nog.

B:
- [x] Bodegraven: zojuist binnen, @roelantc verwerkt… https://www.bodegraven-reeuwijk.nl/uitslag-tweede-kamerverkiezingen-2023

E:

- [x] Ede: https://www.ede.nl/bestuur-en-organisatie/verkiezingen-tweede-kamer

H:
- [x] Haarlem: https://haarlem.nl/verkiezingen-voor-de-tweede-kamer-2023

R:
- [ ] https://www.rozendaal.nl/direct-regelen/burgerzaken/verkiezingen/verkiezingsuitslagen/

W:
- [x] https://www.gemeentewestland.nl/bestuur-en-organisatie/tweede-kamerverkiezingen-22-november-2023

Z:
- [x] https://zandvoort.nl/verkiezingen-voor-de-tweede-kamer-2023

**Comment by roelantc** [comment]
Zou je Assen willen toevoegen? Die sla ik voor nu even over, die hebben de lijst van pdf's weggezet bij een third party waarbij het scrapen van de download url's voor mij een uitdaging is. Heb gekeken of ik de lijst via de API kon ophalen, echter kreeg ik daar helaas een 401 op terug.

Voorbeeld: https://technischbeheerassen.stackstorage.com/s/lsjEEr3WQ1V5L7o3/en

**Comment by Sjors** [comment]
@roelantc ik heb dit issue nu iets nauwer gedefinieerd: alleen gemeentes waarbij de processen-verbaal _ontbreken_. Voor gemeentes waar het scrapen niet lukt, kunnen we aparte issues maken (zoals je deed met #55).

**Comment by roelantc** [comment]
@Sjors zou je de gemeente Ede willen toevoegen? Hier ontbreken de uitslagen nog:
https://www.ede.nl/bestuur-en-organisatie/verkiezingen-tweede-kamer

**Comment by roelantc** [comment]
@Sjors zou je de gemeente Vlaardingen willen afvinken, deze heb ik toegevoegd.

**Comment by Sjors** [comment]
Aangepast (en gelijk ook dingen bij de juiste letter gezet)

**Comment by Eegee** [comment]
Haarlem heeft ook nog geen PV's gepubliceerd

**Comment by Sjors** [comment]
Ik heb een scriptje toegevoegd (push komt zo):

```
2023-TK/0228 Ede.txt
2023-TK/0277 Rozendaal.txt
2023-TK/0296 Wijchen.txt
2023-TK/0340 Rhenen.txt
2023-TK/0363 Amsterdam.txt
2023-TK/0392 Haarlem.txt
2023-TK/0473 Zandvoort.txt
2023-TK/0484 Alphen aan den Rijn.txt
2023-TK/1696 Wijdemeren.txt
2023-TK/1783 Westland.txt
2023-TK/1901 Bodegraven-Reeuwijk.txt
2023-TK/1960 West Betuwe.txt
```

(waarbij ik de mijnstemwijzer en dropbox/googlecloud gemeentes heb weglaten)

**Comment by roelantc** [comment]
Lijkt erop dat de gemeente Bodengraven-Reeuwijk de uitslagen nu wel in pdf vorm op haar website heeft gepubliceerd, zie:
https://www.bodegraven-reeuwijk.nl/uitslag-tweede-kamerverkiezingen-2023

**Comment by Sjors** [comment]
PR welkom, wil jij hem doen?

**Comment by roelantc** [comment]
Yes, ik zal hem straks oppakken

**Comment by Sjors** [comment]
Westerkwartier en Wijdemeren waren door elkaar gehaald. Heb ze nu allebei toegevoegd.

**Comment by roelantc** [comment]
@Sjors er staat een pullrequest klaar voor Ede en Westland. 

Haarlem/Zandvoort hebben inmiddels ook de proces verbalen gepubliceerd. Maar het lukte mij niet om met `urls-from-html.py` resultaat terug te krijgen.

**Comment by Sjors** [comment]
Voor Haarlem en Zandvoort heb ik een aparte issue gemaakt, zie #84.

**Comment by Sjors** [comment]
Rozendaal krijgt een eervolle vermelding als eigen Github issue #85 voor het zijn van de laatste gemeente...
