### ISSUE TITLE
Eerder ingevoerde gemeentes scrape-urls toevoegen

### ISSUE THREAD

**Issue by roelantc** [Sjors/verkiezingen-processen-verbaal#52]
Ik ben bezig met commando's voor gemeentes die ik al eerder heb toegevoegd.

De volgende gemeentes moet ik nog (potentieel) toevoegen:
- [x] https://www.weststellingwerf.nl/uitslag-tweede-kamerverkiezing-2023
- [x] https://www.vlieland.nl/uitslag-tweede-kamerverkiezing-2023-in-de-gemeente-vlieland
- [x] https://www.opsterland.nl/verkiezingen/uitslagen
- [x] https://www.ooststellingwerf.nl/verkiezingen/uitslag
- [x] https://www.leeuwarden.nl/uitslagen-en-processen-verbaal-tweede-kamerverkiezingen-2023
- [x] https://www.harlingen.nl/verkiezingen
- [x] https://www.ameland.nl/verkiezing-tweede-kamer-2023
- [x] https://www.achtkarspelen.nl/uitslag-en-processen-verbaal-tweede-kamerverkiezing-2023-in-achtkarspelen
- [x] https://www.zeewolde.nl/verkiezingen/uitslagen
- [x] https://www.veendam.nl/Onderwerpen/Actueel/Verkiezingen/Processen_verbaal_Tweede_Kamerverkiezingen
- [x] https://www.stadskanaal.nl/inwoners/verkiezingen/verkiezingsuitslagen
- [x] https://www.tiel.nl/processen-verbaal
- [x] https://www.zuidplas.nl/processen-verbaal-van-de-stembureaus
- [x] https://www.gouda.nl/bestuur-en-organisatie/tweede-kamerverkiezingen/processen-verbaal-tweede-kamerverkiezing
- [x] https://www.zwartewaterland.nl/uitslagen-tweede-kamerverkiezingen-22-november-2023
- [x] https://www.tilburg.nl/gemeente/bestuur/verkiezingen/uitslagen-per-stembureau-tweede-kamer-verkiezingen-2023
- [x] https://www.molenlanden.nl/uitslag-verkiezingen-tweede-kamer-22-november-2023
- [x] https://www.wierden.nl/uitslagen-en-processen-verbaal-tweede-kamerverkiezingen-2023
- [x] https://www.dalfsen.nl/verkiezingen-tweede-kamer
- [x] https://www.voorst.nl/verkiezingen/documenten-verkiezingsuitslagen-tweede-kamer
- [x] https://www.eemnes.nl/Bestuur/Tweede_Kamerverkiezing_op_22_november_2023
- [x] https://www.nederweert.nl/verkiezingsuitslagen-provinciale-staten-2023
- [x] https://www.terschelling.nl/uitslagen-tweede-kamerverkiezingen-22-november-2023
- [x] https://www.middelburg.nl/processen-verbaal-verkiezing
- [x] https://www.gemeentehulst.nl/Verkiezingen/Uitslagen
- [x] https://www.schouwen-duiveland.nl/verkiezingen/processenverbaal-tweede-kamer-verkiezingen-2023
- [x] https://www.kapelle.nl/verkiezingsuitslag#processen-verbaal-verkiezing-tweede-kamer-3311
- [x] https://www.gemeentesluis.nl/Bestuur_en_Organisatie/Verkiezingen
- [x] https://www.terneuzen.nl/Verkiezingen/Processen_verbaal_stembureau_s_N10_1_TK2023
- [x] https://www.aaenhunze.nl/Bestuur/Verkiezingen/Proces_verbalen_Tweede_Kamerverkiezing_2023
- [x] https://www.gemeentealtena.nl/verkiezingen/verkiezingen-tweede-kamer-2023

**Comment by Sjors** [comment]
Prima!

Ik heb zojuist de V gepushed, dus je kan het beste even een pull doen om merge conflicts te vermijden (aangezien je volgens mij wat gemeentes met een V had)

Ik ga zelf nu met "U" aan de slag dus dat zal geen nieuwe conflicts opleveren.

**Comment by Sjors** [comment]
De gemeentes in #53 zijn gemerged. Dat leverde nog 2 extra PV's op.

**Comment by Sjors** [comment]
Overigens, als je moet kiezen qua tijdsbesteding, heb ik de komende dagen liever meer nieuwe gemeentes dan up to date scrape-urls.

**Comment by roelantc** [comment]
Yes, dan focus ik in eerste instantie op nieuwe gemeentes toevoegen.
