### ISSUE TITLE
Bezig met: E

### ISSUE THREAD

**Issue by roelantc** [Sjors/verkiezingen-processen-verbaal#54]
Om dubbel werk te voorkomen, kan je eventueel een Issue zoals deze openen.

**Comment by Sjors** [comment]
Ben benieuwd hoe makkelijker Amsterdam gaat, zie #48

**Comment by roelantc** [comment]
Bij de tweede gemeente (Assen) waarmee ik aan de gang ging lukte het mij niet om de url's te scrapen. Dus ik ben ook benieuwd.

**Comment by Sjors** [comment]
Als een gemeente niet lukt, open gerust een issue dan kijk ik er ook even naar.

**Comment by roelantc** [comment]
Ik was aangekomen bij Bloemendaal, ik sluit hem voor nu even aangezien ik richting het eten ga en even nog wat fysieks wil doen. Wellicht dat ik vanavond en anders morgen weer verder ga.

**Comment by roelantc** [comment]
Ik ga aan de gang met de letter E
