### ISSUE TITLE
Brunssum (veel losse pagina's)

### ISSUE THREAD

**Issue by roelantc** [Sjors/verkiezingen-processen-verbaal#60]
De gemeente Brunssum heeft op verschillende webpagina's de pdf's staan. Daarnaast zijn er duplicaten van bestanden op die webpagina's waarbij de bestandsnaam net anders is maar het wel om hetzelfde bestand gaat. Gezien dit een tijdrovend klusje is en het waarschijnlijk een chaos aan scrape-urls gaat worden voor deze gemeente parkeer ik hem even.

https://www.brunssum.nl/Verkiezingen/Uitslagen_Tweede_Kamer_verkiezingen_2023

**Comment by Sjors** [comment]
Mooi is anders, maar het werkt...
