### ISSUE TITLE
Bernheze (dubbele bestandsnamen, verschillende bestanden)

### ISSUE THREAD

**Issue by roelantc** [Sjors/verkiezingen-processen-verbaal#61]
Voor de gemeente Bernheze zijn er bestandsnamen identiek echter de inhoud is verschillend. Hierdoor zal het downloaden van de pdf's voor deze gemeente involledig zijn.

Wellicht in `download.sh` bestanden renamen met een versie o.i.d. voor deze gemeente.

**Comment by Sjors** [comment]
Is de uitzondering die ik voor Arnhem heb gebouwd geschikt hiervoor? Zie `0202)` in `download.sh`.
