### ISSUE TITLE
Losser, Oosterhout, Nissewaard

### ISSUE THREAD

**Issue by Sjors** [Sjors/verkiezingen-processen-verbaal#62]
Fancy graphische applicatie waarbij je één voor één de bestanden moet aanklikken, previewen en dan downloaden. Zo te zien dezelfde software.

* https://mijnstembureau-losser.nl/uitslagen/tk/totaal
* https://www.mijnstembureau-oosterhout.nl/uitslagen/tk/download
* https://stembureau-nissewaard.nl/uitslagen/tk/download

**Comment by roelantc** [comment]
Ah ja, een beetje hetzelfde verhaal als #55

**Comment by Sjors** [comment]
Het zijn er al drie tot nog toe, dus maar eens een oproepje geplaatst: https://twitter.com/provoost/status/1728478045755851234

**Comment by Eegee** [comment]
Ik ben bezig met een python script om deze sites te verwerken

**Comment by Sjors** [comment]
Dankje, ik kom er vanavond niet meer aan toe maar morgen wel.

**Comment by Eegee** [comment]
M'n pull-request https://github.com/Sjors/verkiezingen-processen-verbaal/pull/70 staat er nu.
Hopelijk kun je er iets mee.
Het inpassen in het downloadscript zou ik aan jou willen overlaten, misschien wil je dit Python-script ook wel meer of minder laten doen. Het kan in ieder geval als basis dienen.

**Comment by Sjors** [comment]
Dankje. Ik heb er een apart bash scriptje aan toegevoegd voor die 3 gemeentes.
