### ISSUE TITLE
Letters TODO

### ISSUE THREAD

**Issue by Sjors** [Sjors/verkiezingen-processen-verbaal#64]
* [x] B @roelantc 
* [x] C @roelantc
* [x] D #54 
* [x] E #54 
* [x] G @Eegee #74  
* [x] H #76 
* [x] I @Sjors
* [x] K @Sjors #50 
* [x] L @Sjors 
* [x] M @Sjors

Zie de "Bezig met" issues voor letters waar al aan gewerkt wordt.

Als er bij een gemeente al URL's in het tekstbestand staan, is die al aan de beurt geweest, zie #52.

**Comment by roelantc** [comment]
B is nu klaar, op de openstaande issue na. Ik ga verder met C

**Comment by roelantc** [comment]
C is nu klaar, ben nu bezig met D

**Comment by Eegee** [comment]
Ik ben aan G gestart, bezig...

**Comment by Sjors** [comment]
Ik pak de K op

**Comment by Sjors** [comment]
Nadat alle letters compleet zijn, moet ik nog even kijken of er nog gemeentes ontbreken. Dus welke `.txt` files nog leeg zijn, m.u.v. #51 en #62.

**Comment by Sjors** [comment]
Alleen E en H resteren nog!

Ik ga eind van de middag weer verder, mocht er dan nog een letter zijn.

**Comment by Eegee** [comment]
Ik pak H wel op

**Comment by roelantc** [comment]
Ik pak E op: zie #54

**Comment by roelantc** [comment]
Ik ga verder met #52

**Comment by roelantc** [comment]
Issue #52 is ook grotendeels opgepakt, op de letter H na aangezien @Eegee hiermee bezig is.
Ik werp nog even een blik op #51 of er gemeenten zijn die inmiddels wel een publicatie hebben.

**Comment by roelantc** [comment]
Ik wacht het even verder af, er staat in ieder geval een pullrequest klaar met de wijzigingen van de afgelopen uren.
