### ISSUE TITLE
Download Hulst, Aa en Hunze, Eemnes

### ISSUE THREAD

**Issue by Sjors** [Sjors/verkiezingen-processen-verbaal#8]
Voorbeeld URL:

```
https://www.gemeentehulst.nl/dsresource?objectid=dd6ccc49-5fdc-4540-8ad3-14e789a67309&type=pdf&&
```

Dit levert "dsresource" als bestandsnaam waardoor ze niet uniek zijn.

TODO: download script aanpassen om bv. de `objectid` mee te nemen in de bestandsnaam.

**Comment by Eegee** [comment]
Ze doen iets a la MIME in e-mail, met een Content-Disposition HTTP-header zoals bijv. 
`attachment;filename="0677_stembureau_1_Stadhuis_corrigendum_TK23.pdf"`

**Comment by Sjors** [comment]
Ok, dat zou `wget` met `--content-disposition` aan moeten kunnen. Ik moet alleen een manier hebben om niet steeds alles opnieuw te downloaden. Misschien maar gewoon het aantal bestanden in de folder tellen.
