### ISSUE TITLE
Haarlem & Zandvoort

### ISSUE THREAD

**Issue by Sjors** [Sjors/verkiezingen-processen-verbaal#84]
Deze staan op een cloud drive van Pleio.

Ik heb zelf vooralsnog maar gewoon ~de zip bestanden gedownload~. De zip bestanden bevatten een XML bestand, uhh.

**Comment by Eegee** [comment]
Ik had al even gekeken, maar ziet er redelijk dramatisch uit om (vlug) geautomatiseerd te downloaden. De webapp wordt vanuit javascript opgebouwd, de bulkdownload-functie geeft een timeout of 503 of iets dergelijks als je alles in een keer wilt downloaden, kon ook zo gauw niks van een API vinden, dan zou je haast op browser automation uitkomen, maar dat lijkt me ook niets.
Ik zie dat er GraphQL wordt gebruikt om het e.e.a. op te vragen, maar daar heb ik geen verstand van, en om dat nou eventjes helemaal te gaan leren...

**Comment by Eegee** [comment]
Zie https://github.com/Sjors/verkiezingen-processen-verbaal/pull/86
